### ISSUE TITLE
🐛 [BUG] Half precision kernels not implemented for CPU

### ISSUE THREAD

**Issue by soodoshll** [ise-uiuc/nnsmith#84]
### Description

Hi!

When trying to run NNSmith on TorchJIT, I encountered errors like

```
ERROR   fuzz   - `make_testcase` failed with seed 1412986392. It can be NNSmith or Generator (torch) bug.
ERROR   fuzz   - Traceback (most recent call last):
  File "nnsmith/cli/fuzz.py", line 215, in run
    testcase = self.make_testcase(seed)
  File "nnsmith/cli/fuzz.py", line 187, in make_testcase
    model.refine_weights()  # either random generated or gradient-based.
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/__init__.py", line 40, in refine_weights
    _, inputs = searcher.search(
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/input_gen.py", line 56, in search
    res = self.search_one(cur_input, max_time_ms)
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/input_gen.py", line 110, in search_one
    return SamplingSearch.search_one(self, start_inp, timeout_ms)
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/input_gen.py", line 70, in search_one
    _ = self.net(**start_inp)
  File "/home/su/accdiff/thirdparty/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/symbolnet.py", line 341, in forward
    output_tensors = inst(*input_tensors)
  File "/home/su/accdiff/thirdparty/pytorch/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/proxy_grad.py", line 108, in forward
    return PGReLUFunc.apply(x)
  File "/home/su/accdiff/thirdparty/pytorch/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/su/accdiff/thirdparty/nnsmith/nnsmith/materialize/torch/proxy_grad.py", line 40, in forward
    return torch.relu(input)
RuntimeError: "clamp_min_scalar_cpu" not implemented for 'Half'
```

### Installation

Source file without edits

### Reproduction

```bash
yes | python nnsmith/cli/fuzz.py --config-dir nnsmith/config/ model.type=torch backend.type=torchjit fuzz.root=fuzz_report debug.viz=true backend.target=cuda
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Version of the front-end framework

torch-2.0.0a0+git062380d

### Back-end engine

torchjit

**Comment by ganler** [comment]
@soodoshll Thanks for reporting this issue!

Could you kindly retry on latest main branch? Should be fixed by https://github.com/ise-uiuc/nnsmith/pull/85

**Comment by ganler** [comment]
You have a good point. My bad I did not well test the GPU part and will figure out how to enable that. Thanks for the input!

**Comment by ganler** [comment]
@soodoshll  Apologies for the delay. We should be able to use `backend.target=cuda` now. Thanks for reporting and please let me know if there are any other issues!
